USE [master]
GO
/****** Object:  Database [MotorcycleDB]    Script Date: 11.04.2018 16:54:48 ******/
CREATE DATABASE [MotorcycleDB]
 CONTAINMENT = NONE
 GO
ALTER DATABASE [MotorcycleDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MotorcycleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MotorcycleDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MotorcycleDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MotorcycleDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MotorcycleDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MotorcycleDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MotorcycleDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MotorcycleDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MotorcycleDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MotorcycleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MotorcycleDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MotorcycleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MotorcycleDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MotorcycleDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MotorcycleDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MotorcycleDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MotorcycleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MotorcycleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MotorcycleDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MotorcycleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MotorcycleDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MotorcycleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MotorcycleDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MotorcycleDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MotorcycleDB] SET  MULTI_USER 
GO
ALTER DATABASE [MotorcycleDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MotorcycleDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MotorcycleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MotorcycleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MotorcycleDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MotorcycleDB', N'ON'
GO
ALTER DATABASE [MotorcycleDB] SET QUERY_STORE = OFF
GO
USE [MotorcycleDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [MotorcycleDB]
GO
/****** Object:  Table [dbo].[PersistedBrands]    Script Date: 11.04.2018 16:54:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersistedBrands](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Description] [varchar](250) NOT NULL,
	[FoundingDate] [datetime] NOT NULL,
	[StyleDescription] [varchar](250) NOT NULL,
	[Picture] [varchar](max) NULL,
 CONSTRAINT [PK_PersistedBrands] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersistedModelPerson]    Script Date: 11.04.2018 16:54:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersistedModelPerson](
	[PersonId] [int] NOT NULL,
	[ModelId] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersistedModels]    Script Date: 11.04.2018 16:54:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersistedModels](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[ModelSpecification] [varchar](200) NOT NULL,
	[Price] [decimal](19, 4) NOT NULL,
	[Picture] [varchar](max) NULL,
	[BrandID] [int] NOT NULL,
 CONSTRAINT [PK_PersistedModels] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersistedPersons]    Script Date: 11.04.2018 16:54:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersistedPersons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Birthdate] [datetime] NOT NULL,
 CONSTRAINT [PK_PersistedPersons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK__Model__BrandID__25869641]    Script Date: 11.04.2018 16:54:48 ******/
CREATE NONCLUSTERED INDEX [IX_FK__Model__BrandID__25869641] ON [dbo].[PersistedModels]
(
	[BrandID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PersistedModelPerson]  WITH CHECK ADD FOREIGN KEY([ModelId])
REFERENCES [dbo].[PersistedModels] ([Id])
GO
ALTER TABLE [dbo].[PersistedModelPerson]  WITH CHECK ADD FOREIGN KEY([PersonId])
REFERENCES [dbo].[PersistedPersons] ([Id])
GO
ALTER TABLE [dbo].[PersistedModels]  WITH CHECK ADD  CONSTRAINT [FK__Model__BrandID__25869641] FOREIGN KEY([BrandID])
REFERENCES [dbo].[PersistedBrands] ([Id])
GO
ALTER TABLE [dbo].[PersistedModels] CHECK CONSTRAINT [FK__Model__BrandID__25869641]
GO
USE [master]
GO
ALTER DATABASE [MotorcycleDB] SET  READ_WRITE 
GO
