//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToeffToeff.Persistence
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MotorcycleDb : DbContext
    {
        public MotorcycleDb()
            : base("name=MotorcycleDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersistedBrands> PersistedBrands { get; set; }
        public virtual DbSet<PersistedModels> PersistedModels { get; set; }
        public virtual DbSet<PersistedPersons> PersistedPersons { get; set; }
    }
}
