//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToeffToeff.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersistedModelPersons
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int ModelId { get; set; }
    
        public virtual PersistedModels PersistedModels { get; set; }
        public virtual PersistedPersons PersistedPersons { get; set; }
    }
}
