//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToeffToeff.Persistence
{
    using System.Collections.Generic;
    using ToeffToeff.Interfaces.Persistence;

    public partial class PersistedModels : IPersistedModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersistedModels()
        {
            this.PersistedPersons = new HashSet<PersistedPersons>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ModelSpecification { get; set; }
        public decimal Price { get; set; }
        public string Picture { get; set; }
    
        public virtual PersistedBrands PersistedBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersistedPersons> PersistedPersons { get; set; }
    }
}
